from functions.update_group import update_groups
from functions.load_attackers import load_attackers
from functions.load_defenders import load_defenders
from functions.check_colisions import check_colisions
from functions.load_player import load_player
